version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    volumes:
      - .:/code
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres
